routes/web.php
=> added cache clear route

app/Http/Controllers/highlightsController.php, public/css/site.css, resources/views/highlights/landing.blade.php, resources/views/includes/css/css.blade.php, resources/views/includes/structure/parallax.blade.php, resources/views/layouts/layout.blade.php
1. Add parallax x 4
2. Add context slider
3. Amend css
=> Make landing page better

app/Http/Controllers/pagesController.php, resources/views/collections/details.blade.php, resources/views/collections/index.blade.php, resources/views/departments/details.blade.php, resources/views/departments/index.blade.php, resources/views/exhibitions/details.blade.php, resources/views/exhibitions/index.blade.php, resources/views/galleries/gallery.blade.php, resources/views/galleries/index.blade.php, resources/views/includes/structure/nav.blade.php, resources/views/research/index.blade.php, resources/views/research/profile.blade.php, resources/views/research/project.blade.php, resources/views/research/projects.blade.php, routes/web.php
1. About us - departments, collections
2. Visit us - galleries
=> Semantic url restructure

resources/views/news/index.blade.php
=> Remove leading zero from date

app/Console/Kernel.php, app/Http/Controllers/searchController.php, app/Providers/AppServiceProvider.php, public/css/site.css, resources/views/includes/structure/beta.blade.php, resources/views/includes/structure/head.blade.php, resources/views/includes/structure/open.blade.php, resources/views/layouts/exhibitions.blade.php, resources/views/layouts/home.blade.php, resources/views/layouts/layout.blade.php, resources/views/layouts/visitus.blade.php, resources/views/search/results.blade.php
* Add shopify search
* Fix urls in search
* Add open times
* Ditch banner open
=> Add classes and opening

app/Http/Kernel.php, app/Http/Middleware/SecureHeaders.php, composer.json, composer.lock, public/css/site.css, resources/views/includes/structure/footer.blade.php
Add redis config and terms of sale link
=> Middleware

composer.json, composer.lock
=> Upgrade phpfastcache - closes #209

app/Models/StaffProfiles.php
The staff profiles model had use Directus; rather than use DirectUs;
=> Fix case sensitivity

app/Http/Controllers/jekyllController.php, config/missing-page-redirector.php
=> Put in redirect for combs

composer.json, composer.lock
Change to forked php8 version, with latest leaflet maps. This might fix the CI build failure.
=> Remove gonoware maps

resources/views/components/exhibition-card.blade.php
=> Fix badges.

resources/views/components/exhibition-card.blade.php
=> Change key for images

app/Http/Controllers/highlightsController.php, app/View/Components/carouselSlide.php, package-lock.json, package.json, resources/views/components/carousel-slide.blade.php, resources/views/highlights/landing.blade.php, resources/views/includes/css/css.blade.php, resources/views/includes/scripts/javascript.blade.php, resources/views/includes/structure/nav.blade.php
New BS version for the highlights landing page
Update autoprefixer in package.json
Change navbar colour
This closes #310
=> Change carousels on landing page

resources/views/components/associated-curator.blade.php, resources/views/components/audioguide-card.blade.php, resources/views/components/carousel-slide.blade.php, resources/views/components/ciim-card.blade.php, resources/views/components/exhibition-card.blade.php, resources/views/components/exhibition-files.blade.php, resources/views/components/exhibition-thanks.blade.php, resources/views/components/faq.blade.php, resources/views/components/fundraising-card.blade.php, resources/views/components/gallery-card.blade.php, resources/views/components/governance-card.blade.php, resources/views/components/image-card.blade.php, resources/views/components/instagram-card.blade.php, resources/views/components/learning-file-card.blade.php, resources/views/components/learning-profile-card.blade.php, resources/views/components/partner-card.blade.php, resources/views/components/press-card.blade.php, resources/views/components/shopify-card.blade.php, resources/views/components/shopify-live-card.blade.php, resources/views/components/solr-card.blade.php, resources/views/components/spoliation-card.blade.php, resources/views/components/static-image-card.blade.php, resources/views/components/tessitura-production-card.blade.php, resources/views/components/tessitura-production-details-card.blade.php, resources/views/components/ttn-artist.blade.php, resources/views/components/ttn-viewpoints.blade.php, resources/views/components/twitter-card.blade.php, resources/views/components/vacancy.blade.php, resources/views/components/viewpoint.blade.php, resources/views/components/wordpress-card.blade.php
Refactored components
Fix layout for salary
=> Fix components

composer.json, composer.lock
=> Change elastic

app/Http/Controllers/tessituraController.php, app/Models/TessituraEventTypes.php, resources/views/components/tessitura-production-details-card.blade.php
=> Add dynamic method for event types

composer.json, composer.lock, resources/views/includes/structure/footer.blade.php
=> Add linkedin

resources/views/includes/structure/footer.blade.php
=> Added links

resources/views/tessitura/index.blade.php
=> issue-374-sketchfab

app/Models/SearchContentTypes.php, app/Providers/AppServiceProvider.php, app/View/Components/searchContentType.php, app/View/Components/staticImageCard.php, resources/views/components/search-content-type.blade.php, resources/views/errors/404.blade.php, resources/views/errors/500.blade.php, resources/views/includes/elements/learning-files.blade.php, resources/views/includes/elements/mimetype-meta.blade.php, resources/views/includes/elements/mimetype.blade.php, resources/views/search/results.blade.php
=> Add search types config

config/missing-page-redirector.php
=> Change url for currencies of conflict 

CITATION.cff
=> Add citations

resources/views/research/profile.blade.php
=> Amend title

app/Http/Controllers/visitController.php, app/Models/Exhibitions.php, resources/views/visit/index.blade.php
=> Exhibit tiles fix

config/missing-page-redirector.php
Adding redirect for /visit-us/exhibitions/defaced page.
=> Added redirect for exhibitions/defaced.

.gitignore, composer.lock, resources/views/includes/elements/food-and-drink.blade.php, resources/views/layouts/layout.blade.php
Added food-and-drink banner to shopping-and-eating page
Worth noting that I ran composer update here as well
=> Added data/ folder to gitignore

resources/views/pages/landing.blade.php
REF : https://studio24.zendesk.com/agent/tickets/14018
=> hotfix: latest news card add

resources/views/includes/structure/related-pages.blade.php
[Zendesk](https://studio24.zendesk.com/agent/tickets/14039) ticket reference
=> fix: filter out non existing page in related conent component

resources/views/components/home-page-hero.blade.php
Currently deployed to staging for testing
=> fix: remove unwanted button tag

resources/views/exhibitions/index.blade.php
Adjustment to logic on exhibitions page to show current section if no displays are included.
=> Exhibition page logic update

resources/views/components/exhibition-cta.blade.php, resources/views/components/exhibition-hero.blade.php
Additional exhibition requested to have a 'Donate now' button
https://studio24.zendesk.com/agent/tickets/14367
=> fix: additional exhibtion donate button

resources/views/components/exhibition-cta.blade.php
Another exhibition with `Donate now` CTA btn
REF: https://studio24.zendesk.com/agent/tickets/14511
=> feat: exhibition cta btn endpoint add

resources/views/includes/structure/immunity.blade.php
REF: https://studio24.zendesk.com/agent/tickets/14626
=> Add additional card for "de Heem"

resources/views/components/exhibition-cta.blade.php
REF: https://studio24.zendesk.com/agent/tickets/14664
=> Update CTA to display required data for correct exhibition

resources/views/components/exhibition-cta.blade.php
REF: https://studio24.zendesk.com/agent/tickets/14664
=> cta wording change

resources/views/errors/404.blade.php, resources/views/errors/500.blade.php
Fix a small typo in the error message page
=> fix typo in error message

resources/views/components/exhibition-hero.blade.php
REF: https://trello.com/c/El20aRX3/98-dates-on-archived-exhibitions
=> remove conditional display for exhibition start date

resources/views/exhibitions/details.blade.php, resources/views/includes/structure/meta.blade.php, resources/views/support/index.blade.php
REF: https://studio24.zendesk.com/agent/tickets/14823
=> add hero image section to exhibition and support pages

app/TessituraApi.php
The Tessitura v16 update caused this API call to fail. A minor modification was required to get it working again.
=> Fix API request

app/View/Components/exhibitionCard.php, resources/views/components/exhibition-card.blade.php, resources/views/includes/structure/exhibitions.blade.php
REF: https://studio24.zendesk.com/agent/tickets/14909
=> Add support for additional listing images in exhibition cards

resources/views/components/exhibition-cta.blade.php
REF: https://studio24.zendesk.com/agent/tickets/14950
=> donate now cta for 'discovering-duerer' exhibition

resources/views/components/exhibition-cta.blade.php
REF: 
- https://trello.com/c/ecRV589A/96-exhibition-display-toggle-option-exhibition-webpage-template
- https://3.basecamp.com/3091560/buckets/29603078/messages/8522560908#__recording_8592399736
=> Refactor exhibition CTA logic

resources/js/config.js
Adding Meta and TikTok cookie details as well as updated title and description of cookie banner.
All tracking pixels can and should be added using Google Tag Manager.
=> Updated cookie banner

resources/views/visit/index.blade.php
Client requested a change to the <title> to "Plan your visit"
=> Change page title on visit us page
